services:
  - type: web
    name: music-teacher-live
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: your-mongodb-name # Replace with your MongoDB instance name on Render
          property: connectionString
      - key: JWT_SECRET
        sync: false # Set this manually in the Render dashboard